services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: jobboard
      POSTGRES_PASSWORD: jobboard123
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
